# Generated by Django 5.2 on 2025-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.TextField()),
                ('short_url', models.CharField(max_length=255)),
            ],
        ),
    ]
